public class AllOperations {
    
    	Integer a = 30;
        Integer b = 20;
    
    public void DoADD() {
        Integer res = a+b;
        
        System.debug('Result: ' + res);
    }

    
   public void DoSUB() {
        
        Integer res = a-b;
        
        System.debug('Result: ' + res);
        
        
    }
    
    public void DoMUL() {
        
        Integer res = a*b;
        
        System.debug('Result: ' + res);
        
        
    }
    
    public void DoDIV() {
        
        Integer res = a/b;
        
        System.debug('Result: ' + res);
        
        
    }
    
}